# Generated by Django 5.2.6 on 2025-09-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_appointment_reason_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date', 'time')},
        ),
    ]
