# Generated by Django 5.2.6 on 2025-09-19 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathologistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=120, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pathologist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
